#!/bin/sh

# CRUD FUNCTIONS

set -o errexit # Exit immediately if a command exits with a non-zero status.

# Grab the full path to the uf project directory
pear_dir=$(cd $(dirname $0); pwd)
# The dir with all the uf commands
pear_commands_dir=$pear_dir/libexec
usage_command=$pear_commands_dir/usage


# Alias command to the first arg
command=$1

# The full path to the intended command
command_path=$pear_commands_dir/$command

# If no command was given then print usage and exit
test -n "$command" || {
  $usage_command
  exit 0
}

# If intended command does not exist tell the user and exit with error
test -x $command_path || {
  echo "Unknown command: $command"
  $usage_command
  exit 1
}

# Replace the current process with a process created by invoking the command with
# all args except the first (which was the command name)
exec $command_path "${@:2}"