#!/bin/sh

function create_authors_file() {
    authors="./authors.txt"
    touch $authors || exit
}

function add_author() {
    (grep $1 $authors > /dev/null) && exit 1
    echo $1 $2 >> $authors
}

function get_author() {
    author_info=$(head -1 $authors)
}

function cycle_author() {
    sed -i '' -e '1d' $authors
    echo $author_info >> $authors
}

function current_user(){
    echo $author_info
}

function list_users(){
    cat $authors
}

function set_author(){
    echo what
}

# store default user name & email
# list authors // return authors array
# remove author // remove from hash lookup
# reset authors to default // empty authors array

# get user email from their username
function ping_github() {
    user_data=$(curl -i https://api.github.com/users/$1)
}

function pull_email() {
    echo $user_data | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | grep "email" | cut -d':' -f2
}

# DRIVER CODE
create_authors_file
[[ $1 = "add" ]] && add_author $2 $3 && get_author
[[ $1 = "cycle" ]] && get_author && cycle_author
[[ $1 = "me" ]] && current_user
[[ $1 = "list" ]] && list_users
