#!/bin/sh

# CRUD FUNCTIONS
function create_team_file(){
    team="./team.txt"
    touch $team || exit
}

function add_author() {
    (grep $1 $authors > /dev/null) && exit 1
    echo $1 $2 >> $authors
}

function add_teammate(){
    (grep $1 $team > /dev/null) && exit 1
    echo $1 $2 >> $team
}

function cycle_team() {
    sed -i '' -e '1d' $team
    echo $user_info >> $team
}


function list_team(){
    cat $team
}

function current_user(){
    echo $user_info
}

# GETTERS & SETTERS
function get_committer(){
    user_info=$(head -1 $team)
    username=$(echo $user_info | cut -d ' ' -f1)
    email=$(echo $user_info | cut -d ' ' -f2)
}

function set_committer(){
    git config --local user.name $userame
    git config --local user.email $email
}

function set_hook_committer(){
    sed -ie "s/--local user.name/& $username /g" pre-commit.sh
    sed -ie "s/--local user.email/& $email /g" pre-commit.sh
}

function set_author(){
    export GIT_AUTHOR_NAME=$username
    export GIT_AUTHOR_EMAIL=$email
}

function edit_hook(){
    echo what 
}


# STRETCH: GET EMAIL FROM USERNAME
function ping_github() {
    user_data=$(curl -i https://api.github.com/users/$1)
}

function pull_email() {
    echo $user_data | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | grep "email" | cut -d':' -f2
}

# DRIVER CODE
create_team_file
[[ $1 = "add" ]] && add_teammate $2 $3 && get_teammate
[[ $1 = "cycle" ]] && get_committer && cycle_team
[[ $1 = "me" ]] && current_user
[[ $1 = "list" ]] && list_team
[[ $1 = "set" ]] && get_committer && set_committer && set_hook_committer
