#!/bin/sh

# CRUD FUNCTIONS
function create_team_file(){
    team="./team.txt"
    touch $team || exit
}

function create_hook_file(){
    hook="./pre-commit.sh"
    touch $hook
    chmod +x $hook
}

function add_teammate(){
    (grep $1 $team > /dev/null) && exit 1
    echo $1 $2 >> $team
}

function cycle_team() {
    sed -i '' -e '1d' $team
    echo $user_info >> $team
}


function list_team(){
    cat $team
}

function current_user(){
    echo $user_info
}

# GETTERS & SETTERS
function get_committer(){
    committer_info=$(head -1 $team)
    committer_name=$(echo $user_info | cut -d ' ' -f1)
    committer_email=$(echo $user_info | cut -d ' ' -f2)
}

function set_committer(){
    git config --local user.name $committer_name
    git config --local user.email $committer_email
}

function set_hook_committer(){
    sed -ie "s/--local user.name/& $committer_name /g" pre-commit.sh
    sed -ie "s/--local user.email/& $committer_email /g" pre-commit.sh
}

function get_author(){
    author_info=$(head -2 $team)
    author_name=$(echo $author_info | cut -d ' ' -f1)
    author_email=$(echo $author_info | cut -d ' ' -f2)
}

function set_author(){
    export GIT_AUTHOR_NAME=$author_name
    export GIT_AUTHOR_EMAIL=$author_email
}

# STRETCH: GET EMAIL FROM USERNAME
function ping_github() {
    user_data=$(curl -i https://api.github.com/users/$1)
}

function pull_email() {
    echo $user_data | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | grep "email" | cut -d':' -f2
}

# DRIVER CODE
create_team_file
create_hook_file
[[ $1 = "add" ]] && add_teammate $2 $3 && get_committer
[[ $1 = "cycle" ]] && get_committer && cycle_team
[[ $1 = "me" ]] && current_user
[[ $1 = "list" ]] && list_team
[[ $1 = "set" ]] && get_committer && set_committer && set_hook_committer && get_author && set_author
