#!/bin/sh

git_dir=$(git rev-parse --git-dir)

[[ -f $git_dir/hooks/post-commit ]] || pear create-hook-file

# Set author & committer with the arguments provided 
git config --local author.email $1
git config --local user.email $2
