#!/bin/sh

# Get pear emails as a space delimited string
emails=$(pear get-emails)

# Grab author email
author=$(pear get-author)

# Strip author from emails string
emails=$(echo ${emails##$author})

# Append author to end of string
emails=$(echo $emails $author)

# Reset pear emails
git config --local --remove-section pear

# Convert whitespace to newlines & loop through
echo $emails | tr " " "\n" | while read line; do
  # Add emails to pear emails key
  git config --local --add pear.emails $line
done


