#!/bin/sh

if [ $GIT_API_TOKEN ]; then
  json=`curl -H "Authorization: token $GIT_API_TOKEN" -s https://api.github.com/users/$1`
  pear get-field "$json" "name"
else
  json=`curl -s https://api.github.com/users/$1`
  pear get-field "$json" "name"
fi
