#!/bin/sh

if [ $GIT_API_TOKEN ]; then
  json=`curl -H "Authorization: token $GIT_API_TOKEN" -s https://api.github.com/search/users?q=in:email+$1` 
  pear get-field "$json" "login"

else
  json=`curl -s https://api.github.com/search/users?q=in:email+$1`
  pear get-field "$json" "login"
fi
