#!/bin/sh

if [ $GIT_API_TOKEN ]; then
  curl -H "Authorization: token $GIT_API_TOKEN" -s https://api.github.com/search/users?q=in:email+$1 |
    grep "login" |
      sed "s/  \"login\": \"\(.*\)\",$/\1/" |
        head -1 |
          xargs 
           
else
  curl -s https://api.github.com/search/users?q=in:email+$1 |
    grep "login" |
      sed "s/  \"login\": \"\(.*\)\",$/\1/" |
        head -1 |
          xargs 
fi
