#!/bin/sh

git_dir=$(git rev-parse --git-dir)

# Blow away hook, team files, and current local user
rm -f $git_dir"/hooks/post-commit"

# Remove any local git information we have set
pear get-emails > /dev/null 2>&1 &&
  git config --local --remove-section team
  git config --local --remove-section user

exit 0
