#!/bin/sh

# Get full name from GitHub API;
# Otherwise use first part of email as fallback
username=$(pear git-username $1)

if [[ -z $username ]]; then
  name=$(echo $1 | cut -d '@' -f 1)
  pear request-update
else
  name=$(pear git-full-name $username)
fi

echo $name
