#!/bin/sh

# Get full name from GitHub API;
# Otherwise use first part of email as fallback
username=$(pear git-username $1)

if [[ -z $username ]]; then
  pear request-update $1
  name=$(echo $1 | cut -d '@' -f 1)
else
  name=$(pear git-full-name $username)
fi

git config --local --add session.names "$name"
