#!/bin/sh

# Export variable to git subshell to prevent recursion
[ -n "$HOOK_FIRED" ] && exit 0
export HOOK_FIRED=YES

# Set this commit's committer
git config --local user.email $(pear get-committer)
git config --local user.name $(pear get-committer | cut -d '@' -f 1)
 

# Save current author before cycling through the list
author=$(pear get-author)

pear cycle

pear_name=$(pear get-formatted-names)

# The commit line must run last.
git commit --allow-empty --amend --author "$pear_name <$author>" --no-edit --quiet 
