#!/bin/sh

# Export variable to git subshell to prevent recursion
[ -n "$HOOK_FIRED" ] && exit 0
export HOOK_FIRED=YES

# Set this commit's committer
git config --local user.email $(pear get-committer)
git config --local user.name $(pear get-committer | cut -d '@' -f 1)
 

# Save current author before cycling through the list
author=$(pear get-author)
pear1=$(pear get-name $author)

pear cycle

# Get next author so that we can construct Pear name
next_author=$(pear get-author)
pear2=$(pear get-name $next_author)

pear_name="$pear1 & $pear2"

# The commit line must run last.
git commit --allow-empty --amend --author "$pear_name <$author>" --no-edit --quiet 
