#!/bin/sh

# Blow away hook & team files
rm -f $PEAR_WORKING_DIR"/.git/hooks/pre-commit"
rm -f $PEAR_WORKING_DIR"/.git/team.txt"

# Remove any local git information we have set
git config --local --remove-section user
